development:
  adapter: postgresql
  database: afront_development
  pool: 5
  timeout: 5000
test:
  adapter: postgresql
  database: afront_test
  pool: 5
  timeout: 5000

production:
  adapter: postgresql
  database: afront_production
  pool: 5
  timeout: 5000
